[tool.poetry]
name = "red-teaming agent"
version = "0.1.0"
description = ""
authors = ["Konit <Konit.block@protonmail.com>"]
readme = "README.md"
packages = [
    { include = "red_teaning", from = "." },
]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
pydantic = "^2.6.1"
naptha-sdk = {git = "https://github.com/NapthaAI/naptha-sdk.git"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
